### ISSUE TITLE
Release 2.0 to crates.io

### ISSUE THREAD

**Issue by ErwanDL** [routerify/routerify-cors#5]
Do you guys think this repo's 2.0 could be released to crates.io as well ? Thanks a lot :)

**Comment by ErwanDL** [comment]
Hello @rousan, is this doable in the near future ? The work on getting this project to 2.0 seems to have already been done, it would be a shame to not publish it :(

**Comment by rousan** [comment]
@gsserge @seanpianka can you please make a release? Thanks.

**Comment by gsserge** [comment]
2.0.0 is published to crates.io. Apologies for the delay! I will try to go over the rest of the middleware and make sure that the updated versions are published.

**Comment by ErwanDL** [comment]
That's so cool ! Thanks @gsserge and @rousan. BTW, I started some work to update routerify-websocket to v2.0 here (https://github.com/routerify/routerify-websocket/pull/4), but was stuck because stream-body isn't 2.0-compatible yet (causing one example to fail).
